filter:
  paths:
    - application/
  excluded_paths:
    - application/tests/*
    - application/spec/*
    - src/*
    - scripts/*
    - .homestead/*
tools:
  external_code_coverage: false
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer:
    config: { level: psr2 }
checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    php:
      version: 5.6.9
  tests:
    override:
      -
        command: ./application/vendor/bin/phpunit
        coverage:
          file: application/tests/build/clover.xml
          format: php-clover
