filter:
  paths:
    - app/
  excluded_paths:
    - tests/*
    - spec/*
tools:
  external_code_coverage: false
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer:
    config: { level: psr2 }
checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    php: '5.6.9'
  tests:
    before:
      - 'npm cache clean'
    override:
      -
        command: 'php vendor/bin/phpunit --coverage-clover=tests/build/clover.xml'
        coverage:
          file: tests/build/clover.xml
          format: php-clover
