language: php
  php:
    - 5.5
    - 5.6
    - hhvm

before_script:
  - composer self-update
script:
  - cd application
  - composer install --prefer-source
  - ./vendor/bin/phpunit
after_script:
  - cd application
  - php vendor/bin/coveralls -v
